version: '3.8'

services:
  website:
    container_name: helix_website
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./languages:/var/www/html/languages
    user: www-data

  db:
    image: mysql:5.7
    container_name: helix_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: helix_db
      MYSQL_USER: helix_user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
